## Estimator 이해 및 fit(), predict() 메서드
사이킷런은 ml 모델 학습을 위해서 fit()dmf, 학습된 모델 예측을 위해 predict() 메서드를 제공한다. </br>
또 지도학습의 주요 두 축인 classfication과 regression의 다양한 알고리즘을 구현했다.</br>
구현된 클래스 이름은 각각 Classifier, Regressor -> 합쳐서 Estimator (지도 학습의 모든 알고리즘을 구현한 클래스 통칭)</br></br>

cross_val_score()  : evaluation 함수</br>
GridSearchCV : 하이퍼 파라미터 튜닝을 지원하는 함수인데 Estimator를 인자로 받고, 함수 내에서 fit(), predict() 호출해서 평가, 하이퍼 파라미터 수행</br></br>


비지도학습인 차원축소, 클러스터링, 피처 추출(feature extraction) 모두 fit(), transform() 적용</br>
단, fit()은 학습이 아니라 데이터 변환을 위한 사전 구조를 맞추는 작업</br>
실제 작업은 transform 으로 수행</br></br>

사이킷런은 fit() 과 transform()을 하나로 결합한 fit_transform()도 제공

### 개별 키가 가리키는 데이터 세트의 의미
data(ndarray) : 피처의 데이터 세트 </br>
target(ndarray) : 분류 시 레이블 값, 회귀일 때는 숫자 결과값 데이터 세트 </br>
target_names(ndarray or list) : 개별 레이블의 이름 </br>
feature_names(ndarray of list) : 피처의 이름 </br>
DESR(string) : 데이터 세트에 대한 설명과 각 피처의 설명 </br> </br>

feature_names - data 가 한 세트,
target_names - target가 한 세트 라고 보면 됨.


In [2]:
from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris_data)) # bunch 클래스는 파이썬 딕셔너리 자료형과 유사

<class 'sklearn.utils._bunch.Bunch'>


In [3]:
keys = iris_data.keys()
print('붓꽃 데이터 세트의 키들:', keys)

붓꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [4]:
print('\n feature_names의 type : ',type(iris_data.feature_names))
print(' feature_names의 shape:', len(iris_data.feature_names))
print(iris_data.feature_names)


 feature_names의 type :  <class 'list'>
 feature_names의 shape: 4
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [6]:
print('\n target_names의 type : ', type(iris_data.target_names))
print('\n target_names의 shape : ', len(iris_data.target_names))
print(iris_data.target_names)


 target_names의 type :  <class 'numpy.ndarray'>

 target_names의 shape :  3
['setosa' 'versicolor' 'virginica']


In [8]:
print('\n data의 type:', type(iris_data.data))
print(' data의 shape : ',iris_data.data.shape)
print(iris_data['data'])


 data의 type: <class 'numpy.ndarray'>
 data의 shape :  (150, 4)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  

In [9]:
print('\n target의 type : ', type(iris_data.target))
print(' target 의 shape : ', iris_data.target.shape)
print(iris_data.target)


 target의 type :  <class 'numpy.ndarray'>
 target 의 shape :  (150,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
